# Generated by Django 3.0.3 on 2020-02-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icon/%Y%m%d/'),
        ),
    ]
